/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { NiftyBank } from "./NiftyBank";

export { NiftyBank__factory } from "./factories/NiftyBank__factory";
