/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface XConsoleInterface extends utils.Interface {
  functions: {
    "log(address,address,string)": FunctionFragment;
    "logAddress(address)": FunctionFragment;
    "logBool(bool)": FunctionFragment;
    "logBytes(bytes)": FunctionFragment;
    "logBytes1(bytes1)": FunctionFragment;
    "logBytes10(bytes10)": FunctionFragment;
    "logBytes11(bytes11)": FunctionFragment;
    "logBytes12(bytes12)": FunctionFragment;
    "logBytes13(bytes13)": FunctionFragment;
    "logBytes14(bytes14)": FunctionFragment;
    "logBytes15(bytes15)": FunctionFragment;
    "logBytes16(bytes16)": FunctionFragment;
    "logBytes17(bytes17)": FunctionFragment;
    "logBytes18(bytes18)": FunctionFragment;
    "logBytes19(bytes19)": FunctionFragment;
    "logBytes2(bytes2)": FunctionFragment;
    "logBytes20(bytes20)": FunctionFragment;
    "logBytes21(bytes21)": FunctionFragment;
    "logBytes22(bytes22)": FunctionFragment;
    "logBytes23(bytes23)": FunctionFragment;
    "logBytes24(bytes24)": FunctionFragment;
    "logBytes25(bytes25)": FunctionFragment;
    "logBytes26(bytes26)": FunctionFragment;
    "logBytes27(bytes27)": FunctionFragment;
    "logBytes28(bytes28)": FunctionFragment;
    "logBytes29(bytes29)": FunctionFragment;
    "logBytes3(bytes3)": FunctionFragment;
    "logBytes30(bytes30)": FunctionFragment;
    "logBytes31(bytes31)": FunctionFragment;
    "logBytes32(bytes32)": FunctionFragment;
    "logBytes4(bytes4)": FunctionFragment;
    "logBytes5(bytes5)": FunctionFragment;
    "logBytes6(bytes6)": FunctionFragment;
    "logBytes7(bytes7)": FunctionFragment;
    "logBytes8(bytes8)": FunctionFragment;
    "logBytes9(bytes9)": FunctionFragment;
    "logInt(int256)": FunctionFragment;
    "logString(string)": FunctionFragment;
    "logUint(uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "log",
    values: [string, string, string]
  ): string;
  encodeFunctionData(functionFragment: "logAddress", values: [string]): string;
  encodeFunctionData(functionFragment: "logBool", values: [boolean]): string;
  encodeFunctionData(functionFragment: "logBytes", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "logBytes1",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "logBytes10",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "logBytes11",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "logBytes12",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "logBytes13",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "logBytes14",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "logBytes15",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "logBytes16",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "logBytes17",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "logBytes18",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "logBytes19",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "logBytes2",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "logBytes20",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "logBytes21",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "logBytes22",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "logBytes23",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "logBytes24",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "logBytes25",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "logBytes26",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "logBytes27",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "logBytes28",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "logBytes29",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "logBytes3",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "logBytes30",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "logBytes31",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "logBytes32",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "logBytes4",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "logBytes5",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "logBytes6",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "logBytes7",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "logBytes8",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "logBytes9",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "logInt",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "logString", values: [string]): string;
  encodeFunctionData(
    functionFragment: "logUint",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "log", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "logAddress", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "logBool", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "logBytes", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "logBytes1", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "logBytes10", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "logBytes11", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "logBytes12", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "logBytes13", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "logBytes14", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "logBytes15", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "logBytes16", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "logBytes17", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "logBytes18", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "logBytes19", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "logBytes2", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "logBytes20", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "logBytes21", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "logBytes22", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "logBytes23", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "logBytes24", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "logBytes25", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "logBytes26", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "logBytes27", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "logBytes28", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "logBytes29", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "logBytes3", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "logBytes30", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "logBytes31", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "logBytes32", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "logBytes4", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "logBytes5", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "logBytes6", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "logBytes7", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "logBytes8", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "logBytes9", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "logInt", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "logString", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "logUint", data: BytesLike): Result;

  events: {};
}

export interface XConsole extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: XConsoleInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    "log(address,address,string)"(
      p0: string,
      p1: string,
      p2: string,
      overrides?: CallOverrides
    ): Promise<[void]>;

    "log(address,address,address)"(
      p0: string,
      p1: string,
      p2: string,
      overrides?: CallOverrides
    ): Promise<[void]>;

    "log(bool,uint256,address)"(
      p0: boolean,
      p1: BigNumberish,
      p2: string,
      overrides?: CallOverrides
    ): Promise<[void]>;

    "log(string,address,uint256)"(
      p0: string,
      p1: string,
      p2: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[void]>;

    "log(bool,bool,address)"(
      p0: boolean,
      p1: boolean,
      p2: string,
      overrides?: CallOverrides
    ): Promise<[void]>;

    "log(bool,string,uint256)"(
      p0: boolean,
      p1: string,
      p2: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[void]>;

    "log(bool,bool,uint256)"(
      p0: boolean,
      p1: boolean,
      p2: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[void]>;

    "log(address,address,uint256)"(
      p0: string,
      p1: string,
      p2: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[void]>;

    "log(bool,address,bool)"(
      p0: boolean,
      p1: string,
      p2: boolean,
      overrides?: CallOverrides
    ): Promise<[void]>;

    "log(string,uint256,address)"(
      p0: string,
      p1: BigNumberish,
      p2: string,
      overrides?: CallOverrides
    ): Promise<[void]>;

    "log(uint256,bool)"(
      p0: BigNumberish,
      p1: boolean,
      overrides?: CallOverrides
    ): Promise<[void]>;

    "log(uint256,bool,uint256)"(
      p0: BigNumberish,
      p1: boolean,
      p2: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[void]>;

    "log(uint256,bool,bool)"(
      p0: BigNumberish,
      p1: boolean,
      p2: boolean,
      overrides?: CallOverrides
    ): Promise<[void]>;

    "log(address,bool,string)"(
      p0: string,
      p1: boolean,
      p2: string,
      overrides?: CallOverrides
    ): Promise<[void]>;

    "log(bool,bool,string)"(
      p0: boolean,
      p1: boolean,
      p2: string,
      overrides?: CallOverrides
    ): Promise<[void]>;

    "log(bool,bool)"(
      p0: boolean,
      p1: boolean,
      overrides?: CallOverrides
    ): Promise<[void]>;

    "log(address)"(p0: string, overrides?: CallOverrides): Promise<[void]>;

    "log(string,string,string)"(
      p0: string,
      p1: string,
      p2: string,
      overrides?: CallOverrides
    ): Promise<[void]>;

    "log(string,address)"(
      p0: string,
      p1: string,
      overrides?: CallOverrides
    ): Promise<[void]>;

    "log(bool)"(p0: boolean, overrides?: CallOverrides): Promise<[void]>;

    "log(uint256,bool,address)"(
      p0: BigNumberish,
      p1: boolean,
      p2: string,
      overrides?: CallOverrides
    ): Promise<[void]>;

    "log(bool,uint256,uint256)"(
      p0: boolean,
      p1: BigNumberish,
      p2: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[void]>;

    "log(uint256,string,uint256)"(
      p0: BigNumberish,
      p1: string,
      p2: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[void]>;

    "log(bool,uint256)"(
      p0: boolean,
      p1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[void]>;

    "log(string)"(p0: string, overrides?: CallOverrides): Promise<[void]>;

    "log(uint256,uint256,bool)"(
      p0: BigNumberish,
      p1: BigNumberish,
      p2: boolean,
      overrides?: CallOverrides
    ): Promise<[void]>;

    "log(string,string)"(
      p0: string,
      p1: string,
      overrides?: CallOverrides
    ): Promise<[void]>;

    "log(uint256,string,bool)"(
      p0: BigNumberish,
      p1: string,
      p2: boolean,
      overrides?: CallOverrides
    ): Promise<[void]>;

    "log(bool,bool,bool)"(
      p0: boolean,
      p1: boolean,
      p2: boolean,
      overrides?: CallOverrides
    ): Promise<[void]>;

    "log()"(overrides?: CallOverrides): Promise<[void]>;

    "log(string,string,uint256)"(
      p0: string,
      p1: string,
      p2: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[void]>;

    "log(string,uint256,string)"(
      p0: string,
      p1: BigNumberish,
      p2: string,
      overrides?: CallOverrides
    ): Promise<[void]>;

    "log(uint256,address,uint256)"(
      p0: BigNumberish,
      p1: string,
      p2: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[void]>;

    "log(uint256,uint256,address)"(
      p0: BigNumberish,
      p1: BigNumberish,
      p2: string,
      overrides?: CallOverrides
    ): Promise<[void]>;

    "log(bool,address,uint256)"(
      p0: boolean,
      p1: string,
      p2: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[void]>;

    "log(uint256,address,string)"(
      p0: BigNumberish,
      p1: string,
      p2: string,
      overrides?: CallOverrides
    ): Promise<[void]>;

    "log(uint256,string)"(
      p0: BigNumberish,
      p1: string,
      overrides?: CallOverrides
    ): Promise<[void]>;

    "log(address,uint256,bool)"(
      p0: string,
      p1: BigNumberish,
      p2: boolean,
      overrides?: CallOverrides
    ): Promise<[void]>;

    "log(address,string,uint256)"(
      p0: string,
      p1: string,
      p2: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[void]>;

    "log(uint256,address)"(
      p0: BigNumberish,
      p1: string,
      overrides?: CallOverrides
    ): Promise<[void]>;

    "log(uint256,uint256,string)"(
      p0: BigNumberish,
      p1: BigNumberish,
      p2: string,
      overrides?: CallOverrides
    ): Promise<[void]>;

    "log(address,string)"(
      p0: string,
      p1: string,
      overrides?: CallOverrides
    ): Promise<[void]>;

    "log(address,bool)"(
      p0: string,
      p1: boolean,
      overrides?: CallOverrides
    ): Promise<[void]>;

    "log(uint256,string,address)"(
      p0: BigNumberish,
      p1: string,
      p2: string,
      overrides?: CallOverrides
    ): Promise<[void]>;

    "log(address,uint256,address)"(
      p0: string,
      p1: BigNumberish,
      p2: string,
      overrides?: CallOverrides
    ): Promise<[void]>;

    "log(address,uint256)"(
      p0: string,
      p1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[void]>;

    "log(string,bool,bool)"(
      p0: string,
      p1: boolean,
      p2: boolean,
      overrides?: CallOverrides
    ): Promise<[void]>;

    "log(bool,address)"(
      p0: boolean,
      p1: string,
      overrides?: CallOverrides
    ): Promise<[void]>;

    "log(uint256,bool,string)"(
      p0: BigNumberish,
      p1: boolean,
      p2: string,
      overrides?: CallOverrides
    ): Promise<[void]>;

    "log(bool,string)"(
      p0: boolean,
      p1: string,
      overrides?: CallOverrides
    ): Promise<[void]>;

    "log(string,bool,address)"(
      p0: string,
      p1: boolean,
      p2: string,
      overrides?: CallOverrides
    ): Promise<[void]>;

    "log(bool,string,address)"(
      p0: boolean,
      p1: string,
      p2: string,
      overrides?: CallOverrides
    ): Promise<[void]>;

    "log(string,string,address)"(
      p0: string,
      p1: string,
      p2: string,
      overrides?: CallOverrides
    ): Promise<[void]>;

    "log(uint256,address,bool)"(
      p0: BigNumberish,
      p1: string,
      p2: boolean,
      overrides?: CallOverrides
    ): Promise<[void]>;

    "log(address,bool,uint256)"(
      p0: string,
      p1: boolean,
      p2: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[void]>;

    "log(address,uint256,string)"(
      p0: string,
      p1: BigNumberish,
      p2: string,
      overrides?: CallOverrides
    ): Promise<[void]>;

    "log(bool,string,string)"(
      p0: boolean,
      p1: string,
      p2: string,
      overrides?: CallOverrides
    ): Promise<[void]>;

    "log(string,string,bool)"(
      p0: string,
      p1: string,
      p2: boolean,
      overrides?: CallOverrides
    ): Promise<[void]>;

    "log(uint256,string,string)"(
      p0: BigNumberish,
      p1: string,
      p2: string,
      overrides?: CallOverrides
    ): Promise<[void]>;

    "log(string,uint256)"(
      p0: string,
      p1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[void]>;

    "log(address,uint256,uint256)"(
      p0: string,
      p1: BigNumberish,
      p2: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[void]>;

    "log(uint256,address,address)"(
      p0: BigNumberish,
      p1: string,
      p2: string,
      overrides?: CallOverrides
    ): Promise<[void]>;

    "log(string,bool)"(
      p0: string,
      p1: boolean,
      overrides?: CallOverrides
    ): Promise<[void]>;

    "log(bool,uint256,string)"(
      p0: boolean,
      p1: BigNumberish,
      p2: string,
      overrides?: CallOverrides
    ): Promise<[void]>;

    "log(string,address,bool)"(
      p0: string,
      p1: string,
      p2: boolean,
      overrides?: CallOverrides
    ): Promise<[void]>;

    "log(string,bool,uint256)"(
      p0: string,
      p1: boolean,
      p2: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[void]>;

    "log(string,uint256,uint256)"(
      p0: string,
      p1: BigNumberish,
      p2: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[void]>;

    "log(string,uint256,bool)"(
      p0: string,
      p1: BigNumberish,
      p2: boolean,
      overrides?: CallOverrides
    ): Promise<[void]>;

    "log(address,string,bool)"(
      p0: string,
      p1: string,
      p2: boolean,
      overrides?: CallOverrides
    ): Promise<[void]>;

    "log(uint256,uint256,uint256)"(
      p0: BigNumberish,
      p1: BigNumberish,
      p2: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[void]>;

    "log(bool,address,address)"(
      p0: boolean,
      p1: string,
      p2: string,
      overrides?: CallOverrides
    ): Promise<[void]>;

    "log(address,address)"(
      p0: string,
      p1: string,
      overrides?: CallOverrides
    ): Promise<[void]>;

    "log(bool,string,bool)"(
      p0: boolean,
      p1: string,
      p2: boolean,
      overrides?: CallOverrides
    ): Promise<[void]>;

    "log(bool,address,string)"(
      p0: boolean,
      p1: string,
      p2: string,
      overrides?: CallOverrides
    ): Promise<[void]>;

    "log(string,address,string)"(
      p0: string,
      p1: string,
      p2: string,
      overrides?: CallOverrides
    ): Promise<[void]>;

    "log(string,bool,string)"(
      p0: string,
      p1: boolean,
      p2: string,
      overrides?: CallOverrides
    ): Promise<[void]>;

    "log(bool,uint256,bool)"(
      p0: boolean,
      p1: BigNumberish,
      p2: boolean,
      overrides?: CallOverrides
    ): Promise<[void]>;

    "log(address,bool,bool)"(
      p0: string,
      p1: boolean,
      p2: boolean,
      overrides?: CallOverrides
    ): Promise<[void]>;

    "log(address,string,address)"(
      p0: string,
      p1: string,
      p2: string,
      overrides?: CallOverrides
    ): Promise<[void]>;

    "log(address,bool,address)"(
      p0: string,
      p1: boolean,
      p2: string,
      overrides?: CallOverrides
    ): Promise<[void]>;

    "log(uint256,uint256)"(
      p0: BigNumberish,
      p1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[void]>;

    "log(uint256)"(
      p0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[void]>;

    "log(address,string,string)"(
      p0: string,
      p1: string,
      p2: string,
      overrides?: CallOverrides
    ): Promise<[void]>;

    "log(string,address,address)"(
      p0: string,
      p1: string,
      p2: string,
      overrides?: CallOverrides
    ): Promise<[void]>;

    logAddress(p0: string, overrides?: CallOverrides): Promise<[void]>;

    logBool(p0: boolean, overrides?: CallOverrides): Promise<[void]>;

    logBytes(p0: BytesLike, overrides?: CallOverrides): Promise<[void]>;

    logBytes1(p0: BytesLike, overrides?: CallOverrides): Promise<[void]>;

    logBytes10(p0: BytesLike, overrides?: CallOverrides): Promise<[void]>;

    logBytes11(p0: BytesLike, overrides?: CallOverrides): Promise<[void]>;

    logBytes12(p0: BytesLike, overrides?: CallOverrides): Promise<[void]>;

    logBytes13(p0: BytesLike, overrides?: CallOverrides): Promise<[void]>;

    logBytes14(p0: BytesLike, overrides?: CallOverrides): Promise<[void]>;

    logBytes15(p0: BytesLike, overrides?: CallOverrides): Promise<[void]>;

    logBytes16(p0: BytesLike, overrides?: CallOverrides): Promise<[void]>;

    logBytes17(p0: BytesLike, overrides?: CallOverrides): Promise<[void]>;

    logBytes18(p0: BytesLike, overrides?: CallOverrides): Promise<[void]>;

    logBytes19(p0: BytesLike, overrides?: CallOverrides): Promise<[void]>;

    logBytes2(p0: BytesLike, overrides?: CallOverrides): Promise<[void]>;

    logBytes20(p0: BytesLike, overrides?: CallOverrides): Promise<[void]>;

    logBytes21(p0: BytesLike, overrides?: CallOverrides): Promise<[void]>;

    logBytes22(p0: BytesLike, overrides?: CallOverrides): Promise<[void]>;

    logBytes23(p0: BytesLike, overrides?: CallOverrides): Promise<[void]>;

    logBytes24(p0: BytesLike, overrides?: CallOverrides): Promise<[void]>;

    logBytes25(p0: BytesLike, overrides?: CallOverrides): Promise<[void]>;

    logBytes26(p0: BytesLike, overrides?: CallOverrides): Promise<[void]>;

    logBytes27(p0: BytesLike, overrides?: CallOverrides): Promise<[void]>;

    logBytes28(p0: BytesLike, overrides?: CallOverrides): Promise<[void]>;

    logBytes29(p0: BytesLike, overrides?: CallOverrides): Promise<[void]>;

    logBytes3(p0: BytesLike, overrides?: CallOverrides): Promise<[void]>;

    logBytes30(p0: BytesLike, overrides?: CallOverrides): Promise<[void]>;

    logBytes31(p0: BytesLike, overrides?: CallOverrides): Promise<[void]>;

    logBytes32(p0: BytesLike, overrides?: CallOverrides): Promise<[void]>;

    logBytes4(p0: BytesLike, overrides?: CallOverrides): Promise<[void]>;

    logBytes5(p0: BytesLike, overrides?: CallOverrides): Promise<[void]>;

    logBytes6(p0: BytesLike, overrides?: CallOverrides): Promise<[void]>;

    logBytes7(p0: BytesLike, overrides?: CallOverrides): Promise<[void]>;

    logBytes8(p0: BytesLike, overrides?: CallOverrides): Promise<[void]>;

    logBytes9(p0: BytesLike, overrides?: CallOverrides): Promise<[void]>;

    logInt(p0: BigNumberish, overrides?: CallOverrides): Promise<[void]>;

    logString(p0: string, overrides?: CallOverrides): Promise<[void]>;

    logUint(p0: BigNumberish, overrides?: CallOverrides): Promise<[void]>;
  };

  "log(address,address,string)"(
    p0: string,
    p1: string,
    p2: string,
    overrides?: CallOverrides
  ): Promise<void>;

  "log(address,address,address)"(
    p0: string,
    p1: string,
    p2: string,
    overrides?: CallOverrides
  ): Promise<void>;

  "log(bool,uint256,address)"(
    p0: boolean,
    p1: BigNumberish,
    p2: string,
    overrides?: CallOverrides
  ): Promise<void>;

  "log(string,address,uint256)"(
    p0: string,
    p1: string,
    p2: BigNumberish,
    overrides?: CallOverrides
  ): Promise<void>;

  "log(bool,bool,address)"(
    p0: boolean,
    p1: boolean,
    p2: string,
    overrides?: CallOverrides
  ): Promise<void>;

  "log(bool,string,uint256)"(
    p0: boolean,
    p1: string,
    p2: BigNumberish,
    overrides?: CallOverrides
  ): Promise<void>;

  "log(bool,bool,uint256)"(
    p0: boolean,
    p1: boolean,
    p2: BigNumberish,
    overrides?: CallOverrides
  ): Promise<void>;

  "log(address,address,uint256)"(
    p0: string,
    p1: string,
    p2: BigNumberish,
    overrides?: CallOverrides
  ): Promise<void>;

  "log(bool,address,bool)"(
    p0: boolean,
    p1: string,
    p2: boolean,
    overrides?: CallOverrides
  ): Promise<void>;

  "log(string,uint256,address)"(
    p0: string,
    p1: BigNumberish,
    p2: string,
    overrides?: CallOverrides
  ): Promise<void>;

  "log(uint256,bool)"(
    p0: BigNumberish,
    p1: boolean,
    overrides?: CallOverrides
  ): Promise<void>;

  "log(uint256,bool,uint256)"(
    p0: BigNumberish,
    p1: boolean,
    p2: BigNumberish,
    overrides?: CallOverrides
  ): Promise<void>;

  "log(uint256,bool,bool)"(
    p0: BigNumberish,
    p1: boolean,
    p2: boolean,
    overrides?: CallOverrides
  ): Promise<void>;

  "log(address,bool,string)"(
    p0: string,
    p1: boolean,
    p2: string,
    overrides?: CallOverrides
  ): Promise<void>;

  "log(bool,bool,string)"(
    p0: boolean,
    p1: boolean,
    p2: string,
    overrides?: CallOverrides
  ): Promise<void>;

  "log(bool,bool)"(
    p0: boolean,
    p1: boolean,
    overrides?: CallOverrides
  ): Promise<void>;

  "log(address)"(p0: string, overrides?: CallOverrides): Promise<void>;

  "log(string,string,string)"(
    p0: string,
    p1: string,
    p2: string,
    overrides?: CallOverrides
  ): Promise<void>;

  "log(string,address)"(
    p0: string,
    p1: string,
    overrides?: CallOverrides
  ): Promise<void>;

  "log(bool)"(p0: boolean, overrides?: CallOverrides): Promise<void>;

  "log(uint256,bool,address)"(
    p0: BigNumberish,
    p1: boolean,
    p2: string,
    overrides?: CallOverrides
  ): Promise<void>;

  "log(bool,uint256,uint256)"(
    p0: boolean,
    p1: BigNumberish,
    p2: BigNumberish,
    overrides?: CallOverrides
  ): Promise<void>;

  "log(uint256,string,uint256)"(
    p0: BigNumberish,
    p1: string,
    p2: BigNumberish,
    overrides?: CallOverrides
  ): Promise<void>;

  "log(bool,uint256)"(
    p0: boolean,
    p1: BigNumberish,
    overrides?: CallOverrides
  ): Promise<void>;

  "log(string)"(p0: string, overrides?: CallOverrides): Promise<void>;

  "log(uint256,uint256,bool)"(
    p0: BigNumberish,
    p1: BigNumberish,
    p2: boolean,
    overrides?: CallOverrides
  ): Promise<void>;

  "log(string,string)"(
    p0: string,
    p1: string,
    overrides?: CallOverrides
  ): Promise<void>;

  "log(uint256,string,bool)"(
    p0: BigNumberish,
    p1: string,
    p2: boolean,
    overrides?: CallOverrides
  ): Promise<void>;

  "log(bool,bool,bool)"(
    p0: boolean,
    p1: boolean,
    p2: boolean,
    overrides?: CallOverrides
  ): Promise<void>;

  "log()"(overrides?: CallOverrides): Promise<void>;

  "log(string,string,uint256)"(
    p0: string,
    p1: string,
    p2: BigNumberish,
    overrides?: CallOverrides
  ): Promise<void>;

  "log(string,uint256,string)"(
    p0: string,
    p1: BigNumberish,
    p2: string,
    overrides?: CallOverrides
  ): Promise<void>;

  "log(uint256,address,uint256)"(
    p0: BigNumberish,
    p1: string,
    p2: BigNumberish,
    overrides?: CallOverrides
  ): Promise<void>;

  "log(uint256,uint256,address)"(
    p0: BigNumberish,
    p1: BigNumberish,
    p2: string,
    overrides?: CallOverrides
  ): Promise<void>;

  "log(bool,address,uint256)"(
    p0: boolean,
    p1: string,
    p2: BigNumberish,
    overrides?: CallOverrides
  ): Promise<void>;

  "log(uint256,address,string)"(
    p0: BigNumberish,
    p1: string,
    p2: string,
    overrides?: CallOverrides
  ): Promise<void>;

  "log(uint256,string)"(
    p0: BigNumberish,
    p1: string,
    overrides?: CallOverrides
  ): Promise<void>;

  "log(address,uint256,bool)"(
    p0: string,
    p1: BigNumberish,
    p2: boolean,
    overrides?: CallOverrides
  ): Promise<void>;

  "log(address,string,uint256)"(
    p0: string,
    p1: string,
    p2: BigNumberish,
    overrides?: CallOverrides
  ): Promise<void>;

  "log(uint256,address)"(
    p0: BigNumberish,
    p1: string,
    overrides?: CallOverrides
  ): Promise<void>;

  "log(uint256,uint256,string)"(
    p0: BigNumberish,
    p1: BigNumberish,
    p2: string,
    overrides?: CallOverrides
  ): Promise<void>;

  "log(address,string)"(
    p0: string,
    p1: string,
    overrides?: CallOverrides
  ): Promise<void>;

  "log(address,bool)"(
    p0: string,
    p1: boolean,
    overrides?: CallOverrides
  ): Promise<void>;

  "log(uint256,string,address)"(
    p0: BigNumberish,
    p1: string,
    p2: string,
    overrides?: CallOverrides
  ): Promise<void>;

  "log(address,uint256,address)"(
    p0: string,
    p1: BigNumberish,
    p2: string,
    overrides?: CallOverrides
  ): Promise<void>;

  "log(address,uint256)"(
    p0: string,
    p1: BigNumberish,
    overrides?: CallOverrides
  ): Promise<void>;

  "log(string,bool,bool)"(
    p0: string,
    p1: boolean,
    p2: boolean,
    overrides?: CallOverrides
  ): Promise<void>;

  "log(bool,address)"(
    p0: boolean,
    p1: string,
    overrides?: CallOverrides
  ): Promise<void>;

  "log(uint256,bool,string)"(
    p0: BigNumberish,
    p1: boolean,
    p2: string,
    overrides?: CallOverrides
  ): Promise<void>;

  "log(bool,string)"(
    p0: boolean,
    p1: string,
    overrides?: CallOverrides
  ): Promise<void>;

  "log(string,bool,address)"(
    p0: string,
    p1: boolean,
    p2: string,
    overrides?: CallOverrides
  ): Promise<void>;

  "log(bool,string,address)"(
    p0: boolean,
    p1: string,
    p2: string,
    overrides?: CallOverrides
  ): Promise<void>;

  "log(string,string,address)"(
    p0: string,
    p1: string,
    p2: string,
    overrides?: CallOverrides
  ): Promise<void>;

  "log(uint256,address,bool)"(
    p0: BigNumberish,
    p1: string,
    p2: boolean,
    overrides?: CallOverrides
  ): Promise<void>;

  "log(address,bool,uint256)"(
    p0: string,
    p1: boolean,
    p2: BigNumberish,
    overrides?: CallOverrides
  ): Promise<void>;

  "log(address,uint256,string)"(
    p0: string,
    p1: BigNumberish,
    p2: string,
    overrides?: CallOverrides
  ): Promise<void>;

  "log(bool,string,string)"(
    p0: boolean,
    p1: string,
    p2: string,
    overrides?: CallOverrides
  ): Promise<void>;

  "log(string,string,bool)"(
    p0: string,
    p1: string,
    p2: boolean,
    overrides?: CallOverrides
  ): Promise<void>;

  "log(uint256,string,string)"(
    p0: BigNumberish,
    p1: string,
    p2: string,
    overrides?: CallOverrides
  ): Promise<void>;

  "log(string,uint256)"(
    p0: string,
    p1: BigNumberish,
    overrides?: CallOverrides
  ): Promise<void>;

  "log(address,uint256,uint256)"(
    p0: string,
    p1: BigNumberish,
    p2: BigNumberish,
    overrides?: CallOverrides
  ): Promise<void>;

  "log(uint256,address,address)"(
    p0: BigNumberish,
    p1: string,
    p2: string,
    overrides?: CallOverrides
  ): Promise<void>;

  "log(string,bool)"(
    p0: string,
    p1: boolean,
    overrides?: CallOverrides
  ): Promise<void>;

  "log(bool,uint256,string)"(
    p0: boolean,
    p1: BigNumberish,
    p2: string,
    overrides?: CallOverrides
  ): Promise<void>;

  "log(string,address,bool)"(
    p0: string,
    p1: string,
    p2: boolean,
    overrides?: CallOverrides
  ): Promise<void>;

  "log(string,bool,uint256)"(
    p0: string,
    p1: boolean,
    p2: BigNumberish,
    overrides?: CallOverrides
  ): Promise<void>;

  "log(string,uint256,uint256)"(
    p0: string,
    p1: BigNumberish,
    p2: BigNumberish,
    overrides?: CallOverrides
  ): Promise<void>;

  "log(string,uint256,bool)"(
    p0: string,
    p1: BigNumberish,
    p2: boolean,
    overrides?: CallOverrides
  ): Promise<void>;

  "log(address,string,bool)"(
    p0: string,
    p1: string,
    p2: boolean,
    overrides?: CallOverrides
  ): Promise<void>;

  "log(uint256,uint256,uint256)"(
    p0: BigNumberish,
    p1: BigNumberish,
    p2: BigNumberish,
    overrides?: CallOverrides
  ): Promise<void>;

  "log(bool,address,address)"(
    p0: boolean,
    p1: string,
    p2: string,
    overrides?: CallOverrides
  ): Promise<void>;

  "log(address,address)"(
    p0: string,
    p1: string,
    overrides?: CallOverrides
  ): Promise<void>;

  "log(bool,string,bool)"(
    p0: boolean,
    p1: string,
    p2: boolean,
    overrides?: CallOverrides
  ): Promise<void>;

  "log(bool,address,string)"(
    p0: boolean,
    p1: string,
    p2: string,
    overrides?: CallOverrides
  ): Promise<void>;

  "log(string,address,string)"(
    p0: string,
    p1: string,
    p2: string,
    overrides?: CallOverrides
  ): Promise<void>;

  "log(string,bool,string)"(
    p0: string,
    p1: boolean,
    p2: string,
    overrides?: CallOverrides
  ): Promise<void>;

  "log(bool,uint256,bool)"(
    p0: boolean,
    p1: BigNumberish,
    p2: boolean,
    overrides?: CallOverrides
  ): Promise<void>;

  "log(address,bool,bool)"(
    p0: string,
    p1: boolean,
    p2: boolean,
    overrides?: CallOverrides
  ): Promise<void>;

  "log(address,string,address)"(
    p0: string,
    p1: string,
    p2: string,
    overrides?: CallOverrides
  ): Promise<void>;

  "log(address,bool,address)"(
    p0: string,
    p1: boolean,
    p2: string,
    overrides?: CallOverrides
  ): Promise<void>;

  "log(uint256,uint256)"(
    p0: BigNumberish,
    p1: BigNumberish,
    overrides?: CallOverrides
  ): Promise<void>;

  "log(uint256)"(p0: BigNumberish, overrides?: CallOverrides): Promise<void>;

  "log(address,string,string)"(
    p0: string,
    p1: string,
    p2: string,
    overrides?: CallOverrides
  ): Promise<void>;

  "log(string,address,address)"(
    p0: string,
    p1: string,
    p2: string,
    overrides?: CallOverrides
  ): Promise<void>;

  logAddress(p0: string, overrides?: CallOverrides): Promise<void>;

  logBool(p0: boolean, overrides?: CallOverrides): Promise<void>;

  logBytes(p0: BytesLike, overrides?: CallOverrides): Promise<void>;

  logBytes1(p0: BytesLike, overrides?: CallOverrides): Promise<void>;

  logBytes10(p0: BytesLike, overrides?: CallOverrides): Promise<void>;

  logBytes11(p0: BytesLike, overrides?: CallOverrides): Promise<void>;

  logBytes12(p0: BytesLike, overrides?: CallOverrides): Promise<void>;

  logBytes13(p0: BytesLike, overrides?: CallOverrides): Promise<void>;

  logBytes14(p0: BytesLike, overrides?: CallOverrides): Promise<void>;

  logBytes15(p0: BytesLike, overrides?: CallOverrides): Promise<void>;

  logBytes16(p0: BytesLike, overrides?: CallOverrides): Promise<void>;

  logBytes17(p0: BytesLike, overrides?: CallOverrides): Promise<void>;

  logBytes18(p0: BytesLike, overrides?: CallOverrides): Promise<void>;

  logBytes19(p0: BytesLike, overrides?: CallOverrides): Promise<void>;

  logBytes2(p0: BytesLike, overrides?: CallOverrides): Promise<void>;

  logBytes20(p0: BytesLike, overrides?: CallOverrides): Promise<void>;

  logBytes21(p0: BytesLike, overrides?: CallOverrides): Promise<void>;

  logBytes22(p0: BytesLike, overrides?: CallOverrides): Promise<void>;

  logBytes23(p0: BytesLike, overrides?: CallOverrides): Promise<void>;

  logBytes24(p0: BytesLike, overrides?: CallOverrides): Promise<void>;

  logBytes25(p0: BytesLike, overrides?: CallOverrides): Promise<void>;

  logBytes26(p0: BytesLike, overrides?: CallOverrides): Promise<void>;

  logBytes27(p0: BytesLike, overrides?: CallOverrides): Promise<void>;

  logBytes28(p0: BytesLike, overrides?: CallOverrides): Promise<void>;

  logBytes29(p0: BytesLike, overrides?: CallOverrides): Promise<void>;

  logBytes3(p0: BytesLike, overrides?: CallOverrides): Promise<void>;

  logBytes30(p0: BytesLike, overrides?: CallOverrides): Promise<void>;

  logBytes31(p0: BytesLike, overrides?: CallOverrides): Promise<void>;

  logBytes32(p0: BytesLike, overrides?: CallOverrides): Promise<void>;

  logBytes4(p0: BytesLike, overrides?: CallOverrides): Promise<void>;

  logBytes5(p0: BytesLike, overrides?: CallOverrides): Promise<void>;

  logBytes6(p0: BytesLike, overrides?: CallOverrides): Promise<void>;

  logBytes7(p0: BytesLike, overrides?: CallOverrides): Promise<void>;

  logBytes8(p0: BytesLike, overrides?: CallOverrides): Promise<void>;

  logBytes9(p0: BytesLike, overrides?: CallOverrides): Promise<void>;

  logInt(p0: BigNumberish, overrides?: CallOverrides): Promise<void>;

  logString(p0: string, overrides?: CallOverrides): Promise<void>;

  logUint(p0: BigNumberish, overrides?: CallOverrides): Promise<void>;

  callStatic: {
    "log(address,address,string)"(
      p0: string,
      p1: string,
      p2: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "log(address,address,address)"(
      p0: string,
      p1: string,
      p2: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "log(bool,uint256,address)"(
      p0: boolean,
      p1: BigNumberish,
      p2: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "log(string,address,uint256)"(
      p0: string,
      p1: string,
      p2: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "log(bool,bool,address)"(
      p0: boolean,
      p1: boolean,
      p2: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "log(bool,string,uint256)"(
      p0: boolean,
      p1: string,
      p2: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "log(bool,bool,uint256)"(
      p0: boolean,
      p1: boolean,
      p2: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "log(address,address,uint256)"(
      p0: string,
      p1: string,
      p2: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "log(bool,address,bool)"(
      p0: boolean,
      p1: string,
      p2: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    "log(string,uint256,address)"(
      p0: string,
      p1: BigNumberish,
      p2: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "log(uint256,bool)"(
      p0: BigNumberish,
      p1: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    "log(uint256,bool,uint256)"(
      p0: BigNumberish,
      p1: boolean,
      p2: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "log(uint256,bool,bool)"(
      p0: BigNumberish,
      p1: boolean,
      p2: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    "log(address,bool,string)"(
      p0: string,
      p1: boolean,
      p2: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "log(bool,bool,string)"(
      p0: boolean,
      p1: boolean,
      p2: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "log(bool,bool)"(
      p0: boolean,
      p1: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    "log(address)"(p0: string, overrides?: CallOverrides): Promise<void>;

    "log(string,string,string)"(
      p0: string,
      p1: string,
      p2: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "log(string,address)"(
      p0: string,
      p1: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "log(bool)"(p0: boolean, overrides?: CallOverrides): Promise<void>;

    "log(uint256,bool,address)"(
      p0: BigNumberish,
      p1: boolean,
      p2: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "log(bool,uint256,uint256)"(
      p0: boolean,
      p1: BigNumberish,
      p2: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "log(uint256,string,uint256)"(
      p0: BigNumberish,
      p1: string,
      p2: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "log(bool,uint256)"(
      p0: boolean,
      p1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "log(string)"(p0: string, overrides?: CallOverrides): Promise<void>;

    "log(uint256,uint256,bool)"(
      p0: BigNumberish,
      p1: BigNumberish,
      p2: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    "log(string,string)"(
      p0: string,
      p1: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "log(uint256,string,bool)"(
      p0: BigNumberish,
      p1: string,
      p2: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    "log(bool,bool,bool)"(
      p0: boolean,
      p1: boolean,
      p2: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    "log()"(overrides?: CallOverrides): Promise<void>;

    "log(string,string,uint256)"(
      p0: string,
      p1: string,
      p2: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "log(string,uint256,string)"(
      p0: string,
      p1: BigNumberish,
      p2: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "log(uint256,address,uint256)"(
      p0: BigNumberish,
      p1: string,
      p2: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "log(uint256,uint256,address)"(
      p0: BigNumberish,
      p1: BigNumberish,
      p2: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "log(bool,address,uint256)"(
      p0: boolean,
      p1: string,
      p2: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "log(uint256,address,string)"(
      p0: BigNumberish,
      p1: string,
      p2: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "log(uint256,string)"(
      p0: BigNumberish,
      p1: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "log(address,uint256,bool)"(
      p0: string,
      p1: BigNumberish,
      p2: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    "log(address,string,uint256)"(
      p0: string,
      p1: string,
      p2: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "log(uint256,address)"(
      p0: BigNumberish,
      p1: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "log(uint256,uint256,string)"(
      p0: BigNumberish,
      p1: BigNumberish,
      p2: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "log(address,string)"(
      p0: string,
      p1: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "log(address,bool)"(
      p0: string,
      p1: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    "log(uint256,string,address)"(
      p0: BigNumberish,
      p1: string,
      p2: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "log(address,uint256,address)"(
      p0: string,
      p1: BigNumberish,
      p2: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "log(address,uint256)"(
      p0: string,
      p1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "log(string,bool,bool)"(
      p0: string,
      p1: boolean,
      p2: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    "log(bool,address)"(
      p0: boolean,
      p1: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "log(uint256,bool,string)"(
      p0: BigNumberish,
      p1: boolean,
      p2: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "log(bool,string)"(
      p0: boolean,
      p1: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "log(string,bool,address)"(
      p0: string,
      p1: boolean,
      p2: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "log(bool,string,address)"(
      p0: boolean,
      p1: string,
      p2: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "log(string,string,address)"(
      p0: string,
      p1: string,
      p2: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "log(uint256,address,bool)"(
      p0: BigNumberish,
      p1: string,
      p2: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    "log(address,bool,uint256)"(
      p0: string,
      p1: boolean,
      p2: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "log(address,uint256,string)"(
      p0: string,
      p1: BigNumberish,
      p2: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "log(bool,string,string)"(
      p0: boolean,
      p1: string,
      p2: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "log(string,string,bool)"(
      p0: string,
      p1: string,
      p2: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    "log(uint256,string,string)"(
      p0: BigNumberish,
      p1: string,
      p2: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "log(string,uint256)"(
      p0: string,
      p1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "log(address,uint256,uint256)"(
      p0: string,
      p1: BigNumberish,
      p2: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "log(uint256,address,address)"(
      p0: BigNumberish,
      p1: string,
      p2: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "log(string,bool)"(
      p0: string,
      p1: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    "log(bool,uint256,string)"(
      p0: boolean,
      p1: BigNumberish,
      p2: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "log(string,address,bool)"(
      p0: string,
      p1: string,
      p2: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    "log(string,bool,uint256)"(
      p0: string,
      p1: boolean,
      p2: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "log(string,uint256,uint256)"(
      p0: string,
      p1: BigNumberish,
      p2: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "log(string,uint256,bool)"(
      p0: string,
      p1: BigNumberish,
      p2: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    "log(address,string,bool)"(
      p0: string,
      p1: string,
      p2: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    "log(uint256,uint256,uint256)"(
      p0: BigNumberish,
      p1: BigNumberish,
      p2: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "log(bool,address,address)"(
      p0: boolean,
      p1: string,
      p2: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "log(address,address)"(
      p0: string,
      p1: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "log(bool,string,bool)"(
      p0: boolean,
      p1: string,
      p2: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    "log(bool,address,string)"(
      p0: boolean,
      p1: string,
      p2: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "log(string,address,string)"(
      p0: string,
      p1: string,
      p2: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "log(string,bool,string)"(
      p0: string,
      p1: boolean,
      p2: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "log(bool,uint256,bool)"(
      p0: boolean,
      p1: BigNumberish,
      p2: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    "log(address,bool,bool)"(
      p0: string,
      p1: boolean,
      p2: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    "log(address,string,address)"(
      p0: string,
      p1: string,
      p2: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "log(address,bool,address)"(
      p0: string,
      p1: boolean,
      p2: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "log(uint256,uint256)"(
      p0: BigNumberish,
      p1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "log(uint256)"(p0: BigNumberish, overrides?: CallOverrides): Promise<void>;

    "log(address,string,string)"(
      p0: string,
      p1: string,
      p2: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "log(string,address,address)"(
      p0: string,
      p1: string,
      p2: string,
      overrides?: CallOverrides
    ): Promise<void>;

    logAddress(p0: string, overrides?: CallOverrides): Promise<void>;

    logBool(p0: boolean, overrides?: CallOverrides): Promise<void>;

    logBytes(p0: BytesLike, overrides?: CallOverrides): Promise<void>;

    logBytes1(p0: BytesLike, overrides?: CallOverrides): Promise<void>;

    logBytes10(p0: BytesLike, overrides?: CallOverrides): Promise<void>;

    logBytes11(p0: BytesLike, overrides?: CallOverrides): Promise<void>;

    logBytes12(p0: BytesLike, overrides?: CallOverrides): Promise<void>;

    logBytes13(p0: BytesLike, overrides?: CallOverrides): Promise<void>;

    logBytes14(p0: BytesLike, overrides?: CallOverrides): Promise<void>;

    logBytes15(p0: BytesLike, overrides?: CallOverrides): Promise<void>;

    logBytes16(p0: BytesLike, overrides?: CallOverrides): Promise<void>;

    logBytes17(p0: BytesLike, overrides?: CallOverrides): Promise<void>;

    logBytes18(p0: BytesLike, overrides?: CallOverrides): Promise<void>;

    logBytes19(p0: BytesLike, overrides?: CallOverrides): Promise<void>;

    logBytes2(p0: BytesLike, overrides?: CallOverrides): Promise<void>;

    logBytes20(p0: BytesLike, overrides?: CallOverrides): Promise<void>;

    logBytes21(p0: BytesLike, overrides?: CallOverrides): Promise<void>;

    logBytes22(p0: BytesLike, overrides?: CallOverrides): Promise<void>;

    logBytes23(p0: BytesLike, overrides?: CallOverrides): Promise<void>;

    logBytes24(p0: BytesLike, overrides?: CallOverrides): Promise<void>;

    logBytes25(p0: BytesLike, overrides?: CallOverrides): Promise<void>;

    logBytes26(p0: BytesLike, overrides?: CallOverrides): Promise<void>;

    logBytes27(p0: BytesLike, overrides?: CallOverrides): Promise<void>;

    logBytes28(p0: BytesLike, overrides?: CallOverrides): Promise<void>;

    logBytes29(p0: BytesLike, overrides?: CallOverrides): Promise<void>;

    logBytes3(p0: BytesLike, overrides?: CallOverrides): Promise<void>;

    logBytes30(p0: BytesLike, overrides?: CallOverrides): Promise<void>;

    logBytes31(p0: BytesLike, overrides?: CallOverrides): Promise<void>;

    logBytes32(p0: BytesLike, overrides?: CallOverrides): Promise<void>;

    logBytes4(p0: BytesLike, overrides?: CallOverrides): Promise<void>;

    logBytes5(p0: BytesLike, overrides?: CallOverrides): Promise<void>;

    logBytes6(p0: BytesLike, overrides?: CallOverrides): Promise<void>;

    logBytes7(p0: BytesLike, overrides?: CallOverrides): Promise<void>;

    logBytes8(p0: BytesLike, overrides?: CallOverrides): Promise<void>;

    logBytes9(p0: BytesLike, overrides?: CallOverrides): Promise<void>;

    logInt(p0: BigNumberish, overrides?: CallOverrides): Promise<void>;

    logString(p0: string, overrides?: CallOverrides): Promise<void>;

    logUint(p0: BigNumberish, overrides?: CallOverrides): Promise<void>;
  };

  filters: {};

  estimateGas: {
    "log(address,address,string)"(
      p0: string,
      p1: string,
      p2: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "log(address,address,address)"(
      p0: string,
      p1: string,
      p2: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "log(bool,uint256,address)"(
      p0: boolean,
      p1: BigNumberish,
      p2: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "log(string,address,uint256)"(
      p0: string,
      p1: string,
      p2: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "log(bool,bool,address)"(
      p0: boolean,
      p1: boolean,
      p2: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "log(bool,string,uint256)"(
      p0: boolean,
      p1: string,
      p2: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "log(bool,bool,uint256)"(
      p0: boolean,
      p1: boolean,
      p2: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "log(address,address,uint256)"(
      p0: string,
      p1: string,
      p2: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "log(bool,address,bool)"(
      p0: boolean,
      p1: string,
      p2: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "log(string,uint256,address)"(
      p0: string,
      p1: BigNumberish,
      p2: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "log(uint256,bool)"(
      p0: BigNumberish,
      p1: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "log(uint256,bool,uint256)"(
      p0: BigNumberish,
      p1: boolean,
      p2: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "log(uint256,bool,bool)"(
      p0: BigNumberish,
      p1: boolean,
      p2: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "log(address,bool,string)"(
      p0: string,
      p1: boolean,
      p2: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "log(bool,bool,string)"(
      p0: boolean,
      p1: boolean,
      p2: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "log(bool,bool)"(
      p0: boolean,
      p1: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "log(address)"(p0: string, overrides?: CallOverrides): Promise<BigNumber>;

    "log(string,string,string)"(
      p0: string,
      p1: string,
      p2: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "log(string,address)"(
      p0: string,
      p1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "log(bool)"(p0: boolean, overrides?: CallOverrides): Promise<BigNumber>;

    "log(uint256,bool,address)"(
      p0: BigNumberish,
      p1: boolean,
      p2: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "log(bool,uint256,uint256)"(
      p0: boolean,
      p1: BigNumberish,
      p2: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "log(uint256,string,uint256)"(
      p0: BigNumberish,
      p1: string,
      p2: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "log(bool,uint256)"(
      p0: boolean,
      p1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "log(string)"(p0: string, overrides?: CallOverrides): Promise<BigNumber>;

    "log(uint256,uint256,bool)"(
      p0: BigNumberish,
      p1: BigNumberish,
      p2: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "log(string,string)"(
      p0: string,
      p1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "log(uint256,string,bool)"(
      p0: BigNumberish,
      p1: string,
      p2: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "log(bool,bool,bool)"(
      p0: boolean,
      p1: boolean,
      p2: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "log()"(overrides?: CallOverrides): Promise<BigNumber>;

    "log(string,string,uint256)"(
      p0: string,
      p1: string,
      p2: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "log(string,uint256,string)"(
      p0: string,
      p1: BigNumberish,
      p2: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "log(uint256,address,uint256)"(
      p0: BigNumberish,
      p1: string,
      p2: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "log(uint256,uint256,address)"(
      p0: BigNumberish,
      p1: BigNumberish,
      p2: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "log(bool,address,uint256)"(
      p0: boolean,
      p1: string,
      p2: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "log(uint256,address,string)"(
      p0: BigNumberish,
      p1: string,
      p2: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "log(uint256,string)"(
      p0: BigNumberish,
      p1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "log(address,uint256,bool)"(
      p0: string,
      p1: BigNumberish,
      p2: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "log(address,string,uint256)"(
      p0: string,
      p1: string,
      p2: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "log(uint256,address)"(
      p0: BigNumberish,
      p1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "log(uint256,uint256,string)"(
      p0: BigNumberish,
      p1: BigNumberish,
      p2: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "log(address,string)"(
      p0: string,
      p1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "log(address,bool)"(
      p0: string,
      p1: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "log(uint256,string,address)"(
      p0: BigNumberish,
      p1: string,
      p2: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "log(address,uint256,address)"(
      p0: string,
      p1: BigNumberish,
      p2: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "log(address,uint256)"(
      p0: string,
      p1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "log(string,bool,bool)"(
      p0: string,
      p1: boolean,
      p2: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "log(bool,address)"(
      p0: boolean,
      p1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "log(uint256,bool,string)"(
      p0: BigNumberish,
      p1: boolean,
      p2: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "log(bool,string)"(
      p0: boolean,
      p1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "log(string,bool,address)"(
      p0: string,
      p1: boolean,
      p2: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "log(bool,string,address)"(
      p0: boolean,
      p1: string,
      p2: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "log(string,string,address)"(
      p0: string,
      p1: string,
      p2: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "log(uint256,address,bool)"(
      p0: BigNumberish,
      p1: string,
      p2: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "log(address,bool,uint256)"(
      p0: string,
      p1: boolean,
      p2: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "log(address,uint256,string)"(
      p0: string,
      p1: BigNumberish,
      p2: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "log(bool,string,string)"(
      p0: boolean,
      p1: string,
      p2: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "log(string,string,bool)"(
      p0: string,
      p1: string,
      p2: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "log(uint256,string,string)"(
      p0: BigNumberish,
      p1: string,
      p2: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "log(string,uint256)"(
      p0: string,
      p1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "log(address,uint256,uint256)"(
      p0: string,
      p1: BigNumberish,
      p2: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "log(uint256,address,address)"(
      p0: BigNumberish,
      p1: string,
      p2: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "log(string,bool)"(
      p0: string,
      p1: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "log(bool,uint256,string)"(
      p0: boolean,
      p1: BigNumberish,
      p2: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "log(string,address,bool)"(
      p0: string,
      p1: string,
      p2: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "log(string,bool,uint256)"(
      p0: string,
      p1: boolean,
      p2: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "log(string,uint256,uint256)"(
      p0: string,
      p1: BigNumberish,
      p2: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "log(string,uint256,bool)"(
      p0: string,
      p1: BigNumberish,
      p2: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "log(address,string,bool)"(
      p0: string,
      p1: string,
      p2: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "log(uint256,uint256,uint256)"(
      p0: BigNumberish,
      p1: BigNumberish,
      p2: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "log(bool,address,address)"(
      p0: boolean,
      p1: string,
      p2: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "log(address,address)"(
      p0: string,
      p1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "log(bool,string,bool)"(
      p0: boolean,
      p1: string,
      p2: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "log(bool,address,string)"(
      p0: boolean,
      p1: string,
      p2: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "log(string,address,string)"(
      p0: string,
      p1: string,
      p2: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "log(string,bool,string)"(
      p0: string,
      p1: boolean,
      p2: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "log(bool,uint256,bool)"(
      p0: boolean,
      p1: BigNumberish,
      p2: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "log(address,bool,bool)"(
      p0: string,
      p1: boolean,
      p2: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "log(address,string,address)"(
      p0: string,
      p1: string,
      p2: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "log(address,bool,address)"(
      p0: string,
      p1: boolean,
      p2: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "log(uint256,uint256)"(
      p0: BigNumberish,
      p1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "log(uint256)"(
      p0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "log(address,string,string)"(
      p0: string,
      p1: string,
      p2: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "log(string,address,address)"(
      p0: string,
      p1: string,
      p2: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    logAddress(p0: string, overrides?: CallOverrides): Promise<BigNumber>;

    logBool(p0: boolean, overrides?: CallOverrides): Promise<BigNumber>;

    logBytes(p0: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    logBytes1(p0: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    logBytes10(p0: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    logBytes11(p0: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    logBytes12(p0: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    logBytes13(p0: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    logBytes14(p0: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    logBytes15(p0: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    logBytes16(p0: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    logBytes17(p0: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    logBytes18(p0: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    logBytes19(p0: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    logBytes2(p0: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    logBytes20(p0: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    logBytes21(p0: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    logBytes22(p0: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    logBytes23(p0: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    logBytes24(p0: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    logBytes25(p0: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    logBytes26(p0: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    logBytes27(p0: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    logBytes28(p0: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    logBytes29(p0: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    logBytes3(p0: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    logBytes30(p0: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    logBytes31(p0: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    logBytes32(p0: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    logBytes4(p0: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    logBytes5(p0: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    logBytes6(p0: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    logBytes7(p0: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    logBytes8(p0: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    logBytes9(p0: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    logInt(p0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    logString(p0: string, overrides?: CallOverrides): Promise<BigNumber>;

    logUint(p0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    "log(address,address,string)"(
      p0: string,
      p1: string,
      p2: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "log(address,address,address)"(
      p0: string,
      p1: string,
      p2: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "log(bool,uint256,address)"(
      p0: boolean,
      p1: BigNumberish,
      p2: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "log(string,address,uint256)"(
      p0: string,
      p1: string,
      p2: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "log(bool,bool,address)"(
      p0: boolean,
      p1: boolean,
      p2: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "log(bool,string,uint256)"(
      p0: boolean,
      p1: string,
      p2: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "log(bool,bool,uint256)"(
      p0: boolean,
      p1: boolean,
      p2: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "log(address,address,uint256)"(
      p0: string,
      p1: string,
      p2: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "log(bool,address,bool)"(
      p0: boolean,
      p1: string,
      p2: boolean,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "log(string,uint256,address)"(
      p0: string,
      p1: BigNumberish,
      p2: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "log(uint256,bool)"(
      p0: BigNumberish,
      p1: boolean,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "log(uint256,bool,uint256)"(
      p0: BigNumberish,
      p1: boolean,
      p2: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "log(uint256,bool,bool)"(
      p0: BigNumberish,
      p1: boolean,
      p2: boolean,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "log(address,bool,string)"(
      p0: string,
      p1: boolean,
      p2: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "log(bool,bool,string)"(
      p0: boolean,
      p1: boolean,
      p2: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "log(bool,bool)"(
      p0: boolean,
      p1: boolean,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "log(address)"(
      p0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "log(string,string,string)"(
      p0: string,
      p1: string,
      p2: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "log(string,address)"(
      p0: string,
      p1: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "log(bool)"(
      p0: boolean,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "log(uint256,bool,address)"(
      p0: BigNumberish,
      p1: boolean,
      p2: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "log(bool,uint256,uint256)"(
      p0: boolean,
      p1: BigNumberish,
      p2: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "log(uint256,string,uint256)"(
      p0: BigNumberish,
      p1: string,
      p2: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "log(bool,uint256)"(
      p0: boolean,
      p1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "log(string)"(
      p0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "log(uint256,uint256,bool)"(
      p0: BigNumberish,
      p1: BigNumberish,
      p2: boolean,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "log(string,string)"(
      p0: string,
      p1: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "log(uint256,string,bool)"(
      p0: BigNumberish,
      p1: string,
      p2: boolean,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "log(bool,bool,bool)"(
      p0: boolean,
      p1: boolean,
      p2: boolean,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "log()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "log(string,string,uint256)"(
      p0: string,
      p1: string,
      p2: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "log(string,uint256,string)"(
      p0: string,
      p1: BigNumberish,
      p2: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "log(uint256,address,uint256)"(
      p0: BigNumberish,
      p1: string,
      p2: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "log(uint256,uint256,address)"(
      p0: BigNumberish,
      p1: BigNumberish,
      p2: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "log(bool,address,uint256)"(
      p0: boolean,
      p1: string,
      p2: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "log(uint256,address,string)"(
      p0: BigNumberish,
      p1: string,
      p2: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "log(uint256,string)"(
      p0: BigNumberish,
      p1: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "log(address,uint256,bool)"(
      p0: string,
      p1: BigNumberish,
      p2: boolean,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "log(address,string,uint256)"(
      p0: string,
      p1: string,
      p2: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "log(uint256,address)"(
      p0: BigNumberish,
      p1: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "log(uint256,uint256,string)"(
      p0: BigNumberish,
      p1: BigNumberish,
      p2: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "log(address,string)"(
      p0: string,
      p1: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "log(address,bool)"(
      p0: string,
      p1: boolean,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "log(uint256,string,address)"(
      p0: BigNumberish,
      p1: string,
      p2: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "log(address,uint256,address)"(
      p0: string,
      p1: BigNumberish,
      p2: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "log(address,uint256)"(
      p0: string,
      p1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "log(string,bool,bool)"(
      p0: string,
      p1: boolean,
      p2: boolean,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "log(bool,address)"(
      p0: boolean,
      p1: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "log(uint256,bool,string)"(
      p0: BigNumberish,
      p1: boolean,
      p2: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "log(bool,string)"(
      p0: boolean,
      p1: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "log(string,bool,address)"(
      p0: string,
      p1: boolean,
      p2: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "log(bool,string,address)"(
      p0: boolean,
      p1: string,
      p2: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "log(string,string,address)"(
      p0: string,
      p1: string,
      p2: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "log(uint256,address,bool)"(
      p0: BigNumberish,
      p1: string,
      p2: boolean,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "log(address,bool,uint256)"(
      p0: string,
      p1: boolean,
      p2: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "log(address,uint256,string)"(
      p0: string,
      p1: BigNumberish,
      p2: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "log(bool,string,string)"(
      p0: boolean,
      p1: string,
      p2: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "log(string,string,bool)"(
      p0: string,
      p1: string,
      p2: boolean,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "log(uint256,string,string)"(
      p0: BigNumberish,
      p1: string,
      p2: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "log(string,uint256)"(
      p0: string,
      p1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "log(address,uint256,uint256)"(
      p0: string,
      p1: BigNumberish,
      p2: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "log(uint256,address,address)"(
      p0: BigNumberish,
      p1: string,
      p2: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "log(string,bool)"(
      p0: string,
      p1: boolean,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "log(bool,uint256,string)"(
      p0: boolean,
      p1: BigNumberish,
      p2: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "log(string,address,bool)"(
      p0: string,
      p1: string,
      p2: boolean,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "log(string,bool,uint256)"(
      p0: string,
      p1: boolean,
      p2: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "log(string,uint256,uint256)"(
      p0: string,
      p1: BigNumberish,
      p2: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "log(string,uint256,bool)"(
      p0: string,
      p1: BigNumberish,
      p2: boolean,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "log(address,string,bool)"(
      p0: string,
      p1: string,
      p2: boolean,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "log(uint256,uint256,uint256)"(
      p0: BigNumberish,
      p1: BigNumberish,
      p2: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "log(bool,address,address)"(
      p0: boolean,
      p1: string,
      p2: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "log(address,address)"(
      p0: string,
      p1: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "log(bool,string,bool)"(
      p0: boolean,
      p1: string,
      p2: boolean,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "log(bool,address,string)"(
      p0: boolean,
      p1: string,
      p2: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "log(string,address,string)"(
      p0: string,
      p1: string,
      p2: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "log(string,bool,string)"(
      p0: string,
      p1: boolean,
      p2: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "log(bool,uint256,bool)"(
      p0: boolean,
      p1: BigNumberish,
      p2: boolean,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "log(address,bool,bool)"(
      p0: string,
      p1: boolean,
      p2: boolean,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "log(address,string,address)"(
      p0: string,
      p1: string,
      p2: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "log(address,bool,address)"(
      p0: string,
      p1: boolean,
      p2: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "log(uint256,uint256)"(
      p0: BigNumberish,
      p1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "log(uint256)"(
      p0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "log(address,string,string)"(
      p0: string,
      p1: string,
      p2: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "log(string,address,address)"(
      p0: string,
      p1: string,
      p2: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    logAddress(
      p0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    logBool(
      p0: boolean,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    logBytes(
      p0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    logBytes1(
      p0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    logBytes10(
      p0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    logBytes11(
      p0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    logBytes12(
      p0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    logBytes13(
      p0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    logBytes14(
      p0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    logBytes15(
      p0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    logBytes16(
      p0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    logBytes17(
      p0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    logBytes18(
      p0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    logBytes19(
      p0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    logBytes2(
      p0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    logBytes20(
      p0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    logBytes21(
      p0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    logBytes22(
      p0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    logBytes23(
      p0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    logBytes24(
      p0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    logBytes25(
      p0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    logBytes26(
      p0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    logBytes27(
      p0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    logBytes28(
      p0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    logBytes29(
      p0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    logBytes3(
      p0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    logBytes30(
      p0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    logBytes31(
      p0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    logBytes32(
      p0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    logBytes4(
      p0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    logBytes5(
      p0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    logBytes6(
      p0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    logBytes7(
      p0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    logBytes8(
      p0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    logBytes9(
      p0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    logInt(
      p0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    logString(
      p0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    logUint(
      p0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
